import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signInAnonymously, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { collection, deleteDoc, doc, endAt, getCountFromServer, getDoc, getDocs, getFirestore, limit, orderBy, query, serverTimestamp, setDoc, startAfter, startAt, Timestamp, updateDoc, where, writeBatch } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import { firebaseConfig, occurrencesSyncUrl } from "./firebase-config.js?v=20260803-15";

const CLASSES=["6A","6B","6C","7A","7B","7C","8A","8B","8C","9A","9B","9C","1A","1B","1C","2A","2B","3A"];
const SICE_SHEET_ID="1NBSDKzLS3IGBAm0klKWR6iiuLrKCi0pbbqikW6O_G-k";
const PAGE_SIZE=5;
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const state={studentCache:new Map(),students:[],currentClass:"",isMaster:false,occurrences:[],occurrenceDocs:[],occurrencePages:[],occurrencePage:0,occurrenceTotal:0,occurrenceSearchStudent:null,occurrenceSearchMatches:[],occurrenceSearchTimer:null,selectedId:""};
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const escapeHtml=value=>{const div=document.createElement("div");div.textContent=value??"";return div.innerHTML};
const normalize=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\s+/g," ").trim();
const normalizeRa=value=>String(value||"").replace(/\D/g,"").replace(/^0+(?=\d)/,"");
const dateOnly=value=>{const text=String(value||"").slice(0,10);return text.includes("/")?text.split("/").reverse().join("-"):text};
const formatDate=value=>{if(!value)return"—";const[y,m,d]=dateOnly(value).split("-");return d&&m&&y?`${d}/${m}/${y}`:value};
const extractArray=json=>Array.isArray(json)?json:Object.values(json||{}).find(Array.isArray)||[];
const timeOnly=value=>{const text=String(value||"");if(/^\d{1,2}:\d{2}/.test(text))return text.slice(0,5);const date=new Date(text);return Number.isNaN(date.getTime())?text:date.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit",timeZone:"America/Sao_Paulo"})};

function occurrenceTimestamp(value){
  const text=String(value||"").trim();let date;
  if(/^\d{1,2}\/\d{1,2}\/\d{4}/.test(text)){const[d,m,y]=text.split(/[\/\s]/);date=new Date(Number(y),Number(m)-1,Number(d))}else date=new Date(text);
  return Number.isNaN(date.getTime())?Timestamp.fromDate(new Date(2000,0,1)):Timestamp.fromDate(date)
}
const canonicalStudentId=student=>`ra-${normalizeRa(student.ra)}-${normalizeRa(student.digit)||"0"}`;
async function commitOperations(operations){for(let start=0;start<operations.length;start+=350){const batch=writeBatch(db);for(const operation of operations.slice(start,start+350)){if(operation.type==="delete")batch.delete(operation.ref);else batch.set(operation.ref,operation.data,operation.options||{})}await batch.commit()}}
async function fetchJsonFresh(url,attempts=3){let lastError;for(let attempt=1;attempt<=attempts;attempt++){try{const separator=url.includes("?")?"&":"?",response=await fetch(url+separator+"_="+Date.now()+"-"+attempt,{cache:"no-store",redirect:"follow"});if(!response.ok)throw new Error("HTTP "+response.status);return await response.json()}catch(error){lastError=error;if(attempt<attempts)await new Promise(resolve=>setTimeout(resolve,700*attempt))}}throw lastError}
function siceCell(row,index){const cell=row?.c?.[index];return String(cell?.f??cell?.v??"").trim()}
function siceDate(value){const text=String(value||""),br=text.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/),gviz=text.match(/^Date\((\d{4}),(\d{1,2}),(\d{1,2})/);if(br)return`${br[3]}-${br[2].padStart(2,"0")}-${br[1].padStart(2,"0")}`;if(gviz)return`${gviz[1]}-${String(Number(gviz[2])+1).padStart(2,"0")}-${gviz[3].padStart(2,"0")}`;return text.slice(0,10)}
function querySiceClass(classId){return new Promise((resolve,reject)=>{const callback="villaniSice_"+Date.now()+"_"+Math.random().toString(36).slice(2),script=document.createElement("script");let timer;const cleanup=()=>{delete window[callback];script.remove();clearTimeout(timer)};timer=setTimeout(()=>{cleanup();reject(new Error("Tempo esgotado ao ler "+classId))},45000);window[callback]=response=>{cleanup();if(response?.status==="error")reject(new Error(response.errors?.[0]?.detailed_message||"Erro na aba "+classId));else resolve(response?.table)};const params=new URLSearchParams({sheet:classId,range:"A1:J120",tqx:"out:json;responseHandler:"+callback});script.src="https://docs.google.com/spreadsheets/d/"+SICE_SHEET_ID+"/gviz/tq?"+params;script.onerror=()=>{cleanup();reject(new Error("Não foi possível acessar a aba "+classId))};document.head.appendChild(script)})}
function convertSiceClass(classId,table){const students=[],rows=table?.rows||[];for(let index=0;index<rows.length;index++){const row=rows[index],cells=Array.from({length:10},(_,column)=>siceCell(row,column));if(/^N[AÃ]O ATIVOS$/i.test(cells[0]))break;if(!cells[3]||!normalizeRa(cells[4]))continue;students.push({type:cells[0]||(/^[6-9]/.test(classId)?"EF":"EM"),segment:cells[0]||(/^[6-9]/.test(classId)?"EF":"EM"),classId,number:Number(cells[2])||"",name:cells[3],ra:cells[4],digit:cells[5].replace(/\.0+$/,""),tutor:cells[6],birthday:siceDate(cells[7]),age:Number(cells[8])||"",elective:cells[9],active:true,sourceRow:index+2,sourceSystem:"SIGFRE/SICE"})}return students}
async function loadSiceStudents(){const students=[];for(let index=0;index<CLASSES.length;index++){const classId=CLASSES[index];$("#connectionText").textContent=`Lendo SICE ${classId} (${index+1}/${CLASSES.length})`;students.push(...convertSiceClass(classId,await querySiceClass(classId)))}return students}

function adaptStudent(raw,index){const ra=String(raw.ra||raw.RA||""),digit=String(raw.digit||raw.digito||""),status=normalize(raw.situacao||raw.status),explicitActive=raw.active;const active=explicitActive!==undefined?[true,"true",1,"1","sim","ativo"].includes(typeof explicitActive==="string"?normalize(explicitActive):explicitActive):(status?status==="ativo":true);return{id:String(raw.id||`ra-${normalizeRa(ra)}-${normalizeRa(digit)||index}`),name:String(raw.name||raw.nome||"Aluno sem nome"),ra,digit,classId:String(raw.classId||raw.sala||raw.Sala||"").toUpperCase(),number:Number(raw.number||raw.numero)||"",tutor:String(raw.tutor||raw.Tutor||""),elective:String(raw.elective||raw.eletiva1||raw.elective1||""),birthday:String(raw.birthday||raw.nascimento||""),photoUrl:String(raw.photoUrl||raw.foto||""),active}}
function field(raw,keys){for(const key of keys)if(raw[key]!==undefined&&raw[key]!==null)return raw[key];return""}
function adaptOccurrence(raw,index){const ra=String(field(raw,["studentRa","ra","RA"])),name=String(field(raw,["studentName","nome","Nome do Aluno","aluno"]));return{id:String(raw.id||`occ-${index}`),studentId:String(raw.studentId||`ra-${normalizeRa(ra)}`),studentRa:ra,studentName:name,classId:String(field(raw,["classId","Sala","sala"])).toUpperCase(),tutor:String(field(raw,["tutor","Tutor"])),eventDate:dateOnly(field(raw,["eventDate","Data do Fato","dataFato"])),eventTime:String(field(raw,["eventTime","Hora do Fato","horaFato"])),category:String(field(raw,["category","Categoria","tipo"])||"Registro geral"),description:String(field(raw,["description","Descrição","descricao"])),teacher:String(field(raw,["teacher","Professor","professor"])),actionTaken:String(field(raw,["actionTaken","Ação Tomada","acao"]))}}
function drivePhoto(value){if(!value)return"";const text=String(value).trim(),match=text.match(/(?:\/d\/|id=)([-\w]{15,})/),id=match?.[1]||(/^[-\w]{15,}$/.test(text)?text:"");return id?`https://lh3.googleusercontent.com/d/${id}=w600`:text}
function avatar(student,large=false){const src=drivePhoto(student.photoUrl);return src?`<img class="avatar ${large?"large":""}" src="${escapeHtml(src)}" alt="Foto de ${escapeHtml(student.name)}" loading="lazy" data-photo="${escapeHtml(src)}" data-name="${escapeHtml(student.name)}">`:`<span class="avatar fallback ${large?"large":""}">${escapeHtml(student.name.slice(0,2).toUpperCase())}</span>`}
function message(text,error=false){const el=$("#message");el.textContent=text;el.classList.toggle("error",error);el.hidden=!text;if(text)window.scrollTo({top:0,behavior:"smooth"})}
function classOptions(){return CLASSES.map(value=>`<option value="${value}">${value}</option>`).join("")}
function fillClassSelectors(){["classFilter","occurrenceClass","reportClass","formClass"].forEach(id=>$("#"+id).insertAdjacentHTML("beforeend",classOptions()));$("#classCount").textContent=`${CLASSES.length} turmas disponíveis`}

async function loadStudentsForClass(classId,{fresh=false}={}){
  if(!classId)return[];if(!fresh&&state.studentCache.has(classId))return state.studentCache.get(classId);
  const snapshot=await getDocs(query(collection(db,"students"),where("classId","==",classId)));
  const students=snapshot.docs.map((entry,index)=>adaptStudent({id:entry.id,...entry.data()},index)).filter(item=>item.active).sort((a,b)=>(a.number||999)-(b.number||999)||a.name.localeCompare(b.name,"pt-BR"));
  state.studentCache.set(classId,students);return students;
}

async function selectStudentClass(classId,fresh=false){
  state.currentClass=classId;$("#studentSearch").disabled=!classId;if(!classId){state.students=[];$("#studentGrid").innerHTML=`<div class="empty">Selecione uma turma para carregar somente os alunos solicitados.</div>`;$("#resultCount").textContent="0 resultados";return}
  $("#studentGrid").innerHTML=`<div class="empty">Carregando ${classId}...</div>`;
  try{state.students=await loadStudentsForClass(classId,{fresh});renderStudents();$("#studentCount").textContent=state.students.length;$("#classCount").textContent=`alunos carregados da turma ${classId}`}
  catch(error){console.error(error);$("#studentGrid").innerHTML=`<div class="empty">Não foi possível carregar a turma. Confirme se a sincronização do Villani criou os documentos na coleção students.</div>`}
}

function renderStudents(){const term=normalize($("#studentSearch").value),list=state.students.filter(item=>!term||normalize(`${item.name} ${item.ra}`).includes(term));$("#resultCount").textContent=`${list.length} resultados`;$("#studentGrid").innerHTML=list.length?list.map(student=>`<article class="student-card">${avatar(student)}<div><header><h3>${escapeHtml(student.name)}</h3><b>${escapeHtml(student.classId)}</b></header><p>RA ${escapeHtml(student.ra||"—")} ${student.digit?`–${escapeHtml(student.digit)}`:""}</p><dl><div><dt>Tutor</dt><dd>${escapeHtml(student.tutor||"—")}</dd></div><div><dt>Eletiva</dt><dd>${escapeHtml(student.elective||"—")}</dd></div></dl><footer><button data-open-report="${escapeHtml(student.id)}" data-class="${student.classId}">Ver boletim</button><button class="secondary" data-open-occurrences="${escapeHtml(student.id)}" data-class="${student.classId}">Ver ocorrências</button></footer></div></article>`).join(""):`<div class="empty">Nenhum aluno encontrado nesta turma.</div>`;bindDynamic()}

function studentOptions(students){return`<option value="">Todos os alunos</option>`+students.map(item=>`<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)} · RA ${escapeHtml(item.ra)}</option>`).join("")}
async function populateStudentsFor(selectId,classId,allLabel="Selecione o aluno"){
  const select=$("#"+selectId);select.disabled=true;select.innerHTML=`<option value="">Carregando...</option>`;if(!classId){select.innerHTML=`<option value="">${allLabel}</option>`;return[]}
  try{const students=await loadStudentsForClass(classId);select.innerHTML=studentOptions(students);if(allLabel!=="Todos os alunos")select.options[0].textContent=allLabel;select.disabled=false;return students}catch{select.innerHTML=`<option value="">Erro ao carregar</option>`;return[]}
}
function findStudent(id){for(const students of state.studentCache.values()){const found=students.find(item=>item.id===id);if(found)return found}return null}

function occurrenceBaseConstraints(){const constraints=[];const studentId=state.occurrenceSearchStudent?.id||$("#occurrenceStudent").value,classId=$("#occurrenceClass").value;if(studentId)constraints.push(where("studentId","==",studentId));else if(classId)constraints.push(where("classId","==",classId));return constraints}
function activeOccurrenceStudent(){return state.occurrenceSearchStudent||findStudent($("#occurrenceStudent").value)}
function setOccurrenceDateState(disabled){[$("#dateFrom"),$("#dateTo")].forEach(input=>{input.disabled=disabled;input.title=disabled?"Datas ignoradas durante a pesquisa por aluno":""})}
function occurrenceQuery(afterDocument=null,pageSize=PAGE_SIZE){const constraints=[...occurrenceBaseConstraints(),orderBy("createdAt","desc")];if(afterDocument)constraints.push(startAfter(afterDocument));constraints.push(limit(pageSize));return query(collection(db,"occurrences"),...constraints)}

async function resetOccurrencePagination(){state.occurrencePages=[];state.occurrencePage=0;$("#occurrenceList").innerHTML=`<div class="empty">Carregando ocorrências...</div>`;try{const student=activeOccurrenceStudent();if(student){let snapshot=await getDocs(query(collection(db,"occurrences"),where("studentName","==",student.name))),entries=snapshot.docs.map((entry,index)=>({doc:entry,item:adaptOccurrence({id:entry.id,...entry.data()},index)})).filter(entry=>!student.classId||entry.item.classId===student.classId);if(!entries.length){snapshot=await getDocs(query(collection(db,"occurrences"),where("studentId","==",student.id)));entries=snapshot.docs.map((entry,index)=>({doc:entry,item:adaptOccurrence({id:entry.id,...entry.data()},index)}))}entries.sort((a,b)=>`${b.item.eventDate} ${b.item.eventTime}`.localeCompare(`${a.item.eventDate} ${a.item.eventTime}`));state.occurrenceTotal=entries.length;for(let start=0;start<entries.length;start+=PAGE_SIZE){const slice=entries.slice(start,start+PAGE_SIZE);state.occurrencePages.push({docs:slice.map(entry=>entry.doc),items:slice.map(entry=>entry.item)})}if(!state.occurrencePages.length)state.occurrencePages.push({docs:[],items:[]});showOccurrencePage(0);return}const countSnapshot=await getCountFromServer(query(collection(db,"occurrences"),...occurrenceBaseConstraints()));state.occurrenceTotal=countSnapshot.data().count;await loadOccurrencePage(0)}catch(error){console.error(error);$("#occurrenceList").innerHTML=`<div class="empty">Não foi possível consultar as ocorrências. ${escapeHtml(error.code||error.message||"")}</div>`}}
async function loadOccurrencePage(index){
  if(index<0)return;if(state.occurrencePages[index]){showOccurrencePage(index);return}
  const previous=index>0?state.occurrencePages[index-1]:null,after=previous?.docs.at(-1)||null;$("#occurrenceList").innerHTML=`<div class="empty">Carregando página ${index+1}...</div>`;
  const snapshot=await getDocs(occurrenceQuery(after));const page={docs:snapshot.docs,items:snapshot.docs.map((entry,i)=>adaptOccurrence({id:entry.id,...entry.data()},i))};state.occurrencePages[index]=page;showOccurrencePage(index)
}
function showOccurrencePage(index){state.occurrencePage=index;const page=state.occurrencePages[index],student=activeOccurrenceStudent();state.occurrenceDocs=page.docs;state.occurrences=page.items;renderOccurrences();$("#occurrenceCount").textContent=student?`${state.occurrenceTotal} ocorrências de ${student.name}`:`${state.occurrenceTotal} registros`;$("#occurrencePage").textContent=`Página ${index+1} de ${Math.max(1,Math.ceil(state.occurrenceTotal/PAGE_SIZE))}`;$("#previousOccurrence").disabled=index===0;$("#nextOccurrence").disabled=(index+1)*PAGE_SIZE>=state.occurrenceTotal||page.docs.length<PAGE_SIZE}
function renderOccurrences(){const student=activeOccurrenceStudent(),term=student?"":normalize($("#occurrenceSearch").value),from=$("#dateFrom").value,to=$("#dateTo").value,ignoreDates=Boolean(student);const list=state.occurrences.filter(item=>(!term||normalize(`${item.studentName} ${item.studentRa} ${item.description}`).includes(term))&&(ignoreDates||!from||item.eventDate>=from)&&(ignoreDates||!to||item.eventDate<=to));$("#occurrenceList").innerHTML=list.length?list.map(item=>`<article class="occurrence ${state.isMaster?"master-occurrence":""}"><div class="date"><b>${escapeHtml(formatDate(item.eventDate).slice(0,5))}</b><span>${escapeHtml(item.eventTime||"—")}</span></div><div class="occ-body"><header><div><em>${escapeHtml(item.category)}</em><h3>${escapeHtml(item.studentName)}</h3><small>${escapeHtml(item.classId)} · RA ${escapeHtml(item.studentRa||"—")}</small></div>${state.isMaster?`<button class="edit-button" data-edit-occurrence="${escapeHtml(item.id)}">Editar</button>`:""}</header><p>${escapeHtml(item.description||"Sem descrição.")}</p><footer>${item.tutor?`<span>Tutor: <b>${escapeHtml(item.tutor)}</b></span>`:""}${item.teacher?`<span>Professor: <b>${escapeHtml(item.teacher)}</b></span>`:""}${item.actionTaken?`<span>Ação: <b>${escapeHtml(item.actionTaken)}</b></span>`:""}</footer></div></article>`).join(""):`<div class="empty">Nenhuma ocorrência nesta página.</div>`;bindDynamic()}

function showOccurrenceStudentMatches(matches){const box=$("#occurrenceSearchResults");state.occurrenceSearchMatches=matches;box.innerHTML=matches.length?matches.map((student,index)=>`<button type="button" data-occurrence-student-result="${index}"><b>${escapeHtml(student.name)}</b><span>${escapeHtml(student.classId)} · RA ${escapeHtml(student.ra||"—")} · Tutor ${escapeHtml(student.tutor||"—")}</span></button>`).join(""):`<p>Nenhum aluno encontrado.</p>`;box.hidden=false;$$('[data-occurrence-student-result]').forEach(button=>button.onclick=()=>selectOccurrenceSearchStudent(state.occurrenceSearchMatches[Number(button.dataset.occurrenceStudentResult)]))}
async function selectOccurrenceSearchStudent(student){if(!student)return;state.occurrenceSearchStudent=student;$("#occurrenceSearch").value=student.name;$("#occurrenceSearchResults").hidden=true;setOccurrenceDateState(true);await resetOccurrencePagination()}
function clearOccurrenceSearchStudent({reload=true}={}){const hadStudent=Boolean(state.occurrenceSearchStudent);state.occurrenceSearchStudent=null;state.occurrenceSearchMatches=[];$("#occurrenceSearchResults").hidden=true;setOccurrenceDateState(Boolean($("#occurrenceStudent").value));if(hadStudent&&reload)resetOccurrencePagination()}
async function searchOccurrenceStudents(){const input=$("#occurrenceSearch"),term=normalize(input.value);if(state.occurrenceSearchStudent&&term===normalize(state.occurrenceSearchStudent.name))return;if(state.occurrenceSearchStudent)clearOccurrenceSearchStudent({reload:false});if(term.length<3){$("#occurrenceSearchResults").hidden=true;renderOccurrences();return}try{const snapshot=await getDocs(query(collection(db,"students"),orderBy("nameSearch"),startAt(term),endAt(term+"\uf8ff"),limit(8))),matches=snapshot.docs.map((entry,index)=>adaptStudent({id:entry.id,...entry.data()},index));showOccurrenceStudentMatches(matches);const exact=matches.filter(student=>normalize(student.name)===term);if(exact.length===1)await selectOccurrenceSearchStudent(exact[0])}catch(error){console.error(error);$("#occurrenceSearchResults").innerHTML="<p>Sincronize os alunos para habilitar a pesquisa global.</p>";$("#occurrenceSearchResults").hidden=false}}

async function loadReport(student){const content=$("#reportContent");content.className="report-wrap";content.innerHTML=`<div class="empty">Carregando boletim...</div>`;const suffixes=["apb","asb","atb","aqb"],terms=[];for(const suffix of suffixes){try{const response=await fetch(`${student.classId.toLowerCase()}${suffix}.json`,{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json(),values=Array.isArray(data)?data:Object.values(data);terms.push(values.find(item=>normalizeRa(item.ra)===normalizeRa(student.ra))||values.find(item=>normalize(item.nome||item.name)===normalize(student.name))||null)}catch{terms.push(null)}}const subjects=[...new Set(terms.flatMap(term=>term?.disciplinas?Object.keys(term.disciplinas):[]))];content.innerHTML=`<article class="profile">${avatar(student,true)}<div><em>ALUNO ATIVO</em><h2>${escapeHtml(student.name)}</h2><p>RA ${escapeHtml(student.ra||"—")} · Nº ${escapeHtml(student.number||"—")} · ${escapeHtml(student.classId)}</p><dl><div><dt>Tutor</dt><dd>${escapeHtml(student.tutor||"—")}</dd></div><div><dt>Eletiva</dt><dd>${escapeHtml(student.elective||"—")}</dd></div></dl></div></article>${subjects.length?`<div class="table-wrap"><table><thead><tr><th>Disciplina</th>${terms.map((_,i)=>`<th>${i+1}º bimestre</th>`).join("")}</tr></thead><tbody>${subjects.map(subject=>`<tr><td>${escapeHtml(subject)}</td>${terms.map(term=>{const data=term?.disciplinas?.[subject];return`<td><b>${escapeHtml(data?.nota??data?.media??"—")}</b><small>${escapeHtml(data?.faltas??0)} faltas</small></td>`}).join("")}</tr>`).join("")}</tbody></table></div>`:`<div class="empty">Nenhum JSON de boletim foi encontrado para ${escapeHtml(student.classId)}.</div>`}`;bindDynamic()}

async function occurrenceId(ra,date,time,description){const source=[normalizeRa(ra),date,time,normalize(description)].join("|"),bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(source));return`occ-${[...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,"0")).join("").slice(0,32)}`}
function whatsappNumber(classId){return/^(6|7|8|9)[ABC]$/i.test(String(classId).replace(/\s/g,""))?"5519997984511":"5519990020650"}
function whatsappLink(student,values){const text=["*OCORRÊNCIA ESCOLAR*","",`Aluno: ${student.name}`,`RA: ${student.ra}`,`Sala: ${student.classId}`,`Tutor: ${student.tutor||"Não informado"}`,"",`Data do fato: ${formatDate(values.eventDate)}`,`Hora: ${values.eventTime||"Não informada"}`,"",`Professor: ${values.teacher||"Não informado"}`,"","Descrição:",values.description,"","Ação tomada:",values.actionTaken||"Não informada"].join("\n");return`https://wa.me/${whatsappNumber(student.classId)}?text=${encodeURIComponent(text)}&app_absent=0`}

function bindDynamic(){$$('[data-photo]').forEach(img=>img.onclick=()=>{const dialog=$("#photoDialog");dialog.querySelector("img").src=img.dataset.photo;dialog.querySelector("strong").textContent=img.dataset.name;dialog.showModal()});$$('[data-open-report]').forEach(button=>button.onclick=async()=>{$("#reportClass").value=button.dataset.class;await populateStudentsFor("reportStudent",button.dataset.class);$("#reportStudent").value=button.dataset.openReport;openTab("report");loadReport(findStudent(button.dataset.openReport))});$$('[data-open-occurrences]').forEach(button=>button.onclick=async()=>{clearOccurrenceSearchStudent({reload:false});$("#occurrenceSearch").value="";$("#occurrenceClass").value=button.dataset.class;await populateStudentsFor("occurrenceStudent",button.dataset.class,"Todos os alunos");$("#occurrenceStudent").value=button.dataset.openOccurrences;setOccurrenceDateState(true);openTab("occurrences");resetOccurrencePagination()});$$('[data-edit-occurrence]').forEach(button=>button.onclick=()=>openOccurrenceEditor(button.dataset.editOccurrence))}
function openTab(id){$$('.view').forEach(view=>view.classList.toggle("active",view.id===id));$$('.tabs button').forEach(button=>button.classList.toggle("active",button.dataset.tab===id));window.scrollTo({top:0,behavior:"smooth"})}

async function updateSyncStatus(){
  if(!state.isMaster)return;
  try{
    const[studentsSnapshot,occurrencesSnapshot]=await Promise.all([getDoc(doc(db,"settings","students-sync")),getDoc(doc(db,"settings","occurrences-sync"))]);
    if(studentsSnapshot.exists()){const data=studentsSnapshot.data(),date=data.syncedAt?.toDate?data.syncedAt.toDate():null;$("#lastSyncText").textContent=`Alunos: ${date?date.toLocaleString("pt-BR"):"data indisponível"} · ${data.records||0} registros.`}
    if(occurrencesSnapshot.exists()){const data=occurrencesSnapshot.data(),date=data.syncedAt?.toDate?data.syncedAt.toDate():null;$("#lastOccurrenceSyncText").textContent=`Ocorrências: ${date?date.toLocaleString("pt-BR"):"data indisponível"} · ${data.records||0} registros.`}
  }catch{$("#lastSyncText").textContent="Não foi possível consultar as últimas sincronizações."}
}
function setMasterInterface(user){state.isMaster=user?.email==="fernando@villani.app";$("#masterButton").textContent=state.isMaster?"Fernando · Sair":"Acesso master";$("#masterButton").classList.toggle("active",state.isMaster);$("#masterTools").hidden=!state.isMaster;$("#connectionText").textContent=state.isMaster?"Modo master ativo":user?"Firebase conectado":"Consulta pública ativa";if(state.isMaster)updateSyncStatus();renderOccurrences()}
function openOccurrenceEditor(id){if(!state.isMaster)return;const item=state.occurrences.find(entry=>entry.id===id);if(!item)return;$("#editId").value=item.id;$("#editStudentLabel").textContent=`${item.studentName} · ${item.classId} · RA ${item.studentRa}`;$("#editDate").value=item.eventDate;$("#editTime").value=item.eventTime||"";$("#editCategory").value=item.category||"Registro geral";$("#editTeacher").value=item.teacher||"";$("#editDescription").value=item.description||"";$("#editAction").value=item.actionTaken||"";$("#editDialog").showModal()}

$("#classFilter").onchange=event=>selectStudentClass(event.target.value);$("#studentSearch").oninput=renderStudents;
$("#occurrenceClass").onchange=async event=>{clearOccurrenceSearchStudent({reload:false});$("#occurrenceSearch").value="";await populateStudentsFor("occurrenceStudent",event.target.value,"Todos os alunos");setOccurrenceDateState(false);resetOccurrencePagination()};$("#occurrenceStudent").onchange=()=>{clearOccurrenceSearchStudent({reload:false});$("#occurrenceSearch").value="";setOccurrenceDateState(Boolean($("#occurrenceStudent").value));resetOccurrencePagination()};$("#occurrenceSearch").oninput=()=>{clearTimeout(state.occurrenceSearchTimer);state.occurrenceSearchTimer=setTimeout(searchOccurrenceStudents,350)};[$("#dateFrom"),$("#dateTo")].forEach(input=>input.onchange=renderOccurrences);
$("#previousOccurrence").onclick=()=>loadOccurrencePage(state.occurrencePage-1);$("#nextOccurrence").onclick=()=>loadOccurrencePage(state.occurrencePage+1);
$("#reportClass").onchange=event=>populateStudentsFor("reportStudent",event.target.value,"Selecione um aluno");$("#reportStudent").onchange=event=>{const student=findStudent(event.target.value);if(student)loadReport(student)};
$("#formClass").onchange=event=>populateStudentsFor("formStudent",event.target.value,"Selecione o aluno");$("#formStudent").onchange=event=>{const student=findStudent(event.target.value),box=$("#selectedStudent");if(!student){box.hidden=true;return}box.innerHTML=`${avatar(student)}<div><b>${escapeHtml(student.name)}</b><span>${student.classId} · RA ${escapeHtml(student.ra)} · Tutor ${escapeHtml(student.tutor||"—")}</span></div>`;box.hidden=false;bindDynamic()};
$$('.tabs button').forEach(button=>button.onclick=()=>{openTab(button.dataset.tab);if(button.dataset.tab==="occurrences"&&!state.occurrencePages.length)resetOccurrencePagination()});$("#eventDate").value=new Date().toISOString().slice(0,10);$("#photoDialog button").onclick=()=>$("#photoDialog").close();

$("#masterButton").onclick=async()=>{if(state.isMaster){await signOut(auth);await signInAnonymously(auth);message("Modo master encerrado.");return}$("#masterError").hidden=true;$("#masterPassword").value="";$("#masterDialog").showModal();setTimeout(()=>$("#masterPassword").focus(),100)};$("#masterDialog .dialog-close").onclick=()=>$("#masterDialog").close();$("#editDialog .dialog-close").onclick=()=>$("#editDialog").close();
$("#syncStudentsButton").onclick=async()=>{
  if(!state.isMaster||!confirm("Ler as 19 abas da planilha SIGFRE/SICE e atualizar somente os alunos ativos no Firebase?"))return;
  const button=$("#syncStudentsButton");let syncStage="renovar a credencial master";button.disabled=true;button.textContent="Sincronizando...";$("#connectionText").textContent="Atualizando alunos";
  try{
    await auth.currentUser.getIdToken(true);syncStage="ler as 18 turmas do SIGFRE/SICE";const raw=await loadSiceStudents();if(!raw.length)throw new Error("A planilha SICE respondeu sem alunos");
    const uniqueStudents=new Map();raw.map(adaptStudent).filter(item=>item.active&&item.name&&normalizeRa(item.ra)).forEach(student=>{const id=canonicalStudentId(student);uniqueStudents.set(id,{...student,id,active:true,nameSearch:normalize(student.name)})});
    syncStage="ler o resumo anterior dos alunos";
    const previousSync=await getDoc(doc(db,"settings","students-sync")),operations=[],activeIds=[...uniqueStudents.keys()];
    let existingSnapshot=null;if(previousSync.data()?.sourceSystem!=="SIGFRE/SICE"){syncStage="migrar fotos e cadastros para os IDs corretos do SICE";existingSnapshot=await getDocs(collection(db,"students"));const photosByKey=new Map(),photosByName=new Map();existingSnapshot.docs.forEach((entry,index)=>{const student=adaptStudent({id:entry.id,...entry.data()},index);if(!student.photoUrl)return;photosByKey.set(normalizeRa(student.ra)+normalizeRa(student.digit),student.photoUrl);photosByName.set(student.classId+"|"+normalize(student.name),student.photoUrl)});uniqueStudents.forEach(student=>{student.photoUrl=photosByKey.get(normalizeRa(student.ra)+normalizeRa(student.digit))||photosByName.get(student.classId+"|"+normalize(student.name))||student.photoUrl})}
    for(const student of uniqueStudents.values()){const data={...student,syncSource:"SIGFRE/SICE",syncedAt:serverTimestamp()};if(!data.photoUrl)delete data.photoUrl;operations.push({type:"set",ref:doc(db,"students",student.id),data,options:{merge:true}})}
    if(existingSnapshot)existingSnapshot.docs.forEach(entry=>{if(!uniqueStudents.has(entry.id))operations.push({type:"delete",ref:entry.ref})});else if(Array.isArray(previousSync.data()?.activeIds))previousSync.data().activeIds.forEach(id=>{if(!uniqueStudents.has(id))operations.push({type:"delete",ref:doc(db,"students",id)})});
    syncStage="gravar "+uniqueStudents.size+" alunos ativos no Firestore";await commitOperations(operations);const written=uniqueStudents.size,removed=operations.filter(item=>item.type==="delete").length;
    const studentIndex=Object.fromEntries([...uniqueStudents.values()].map(student=>[normalizeRa(student.ra),{id:student.id,name:student.name,ra:student.ra,digit:student.digit,classId:student.classId,tutor:student.tutor}]));
    syncStage="salvar o índice e o resumo dos alunos";
    const metadataBatch=writeBatch(db);for(const classId of CLASSES)metadataBatch.set(doc(db,"classes",classId),{id:classId,name:classId,year:2026,active:true,syncSource:"SIGFRE/SICE"},{merge:true});metadataBatch.set(doc(db,"settings","student-index"),{students:studentIndex,records:written,sourceSystem:"SIGFRE/SICE",syncedAt:serverTimestamp()});metadataBatch.set(doc(db,"settings","students-sync"),{records:written,activeIds,sourceSystem:"SIGFRE/SICE",sheetId:SICE_SHEET_ID,syncedAt:serverTimestamp(),syncedBy:"fernando@villani.app"},{merge:true});await metadataBatch.commit();
    state.studentCache.clear();if(state.currentClass)await selectStudentClass(state.currentClass,true);$("#studentCount").textContent=written;$("#connectionText").textContent="Sincronização concluída";$("#lastSyncText").textContent=`Sincronização concluída agora · ${written} alunos ativos do SICE.`;message(`${written} alunos ativos do SICE mantidos; ${removed} documentos antigos removidos. Sincronize as ocorrências para atualizar os vínculos aos novos IDs.`);
  }catch(error){console.error("Falha ao "+syncStage,error);$("#connectionText").textContent="Falha na sincronização";const detail=[error.code,error.message].filter(Boolean).join(" — ");message("Falha ao "+syncStage+(detail?": "+detail:"")+".",true)}finally{button.disabled=false;button.textContent="Sincronizar alunos"}
};
$("#syncOccurrencesButton").onclick=async()=>{
  if(!state.isMaster||!confirm("Importar e atualizar no Firebase as ocorrências antigas da planilha?"))return;
  const button=$("#syncOccurrencesButton");let syncStage="renovar a credencial master";button.disabled=true;button.textContent="Sincronizando...";$("#connectionText").textContent="Atualizando ocorrências";
  try{
    await auth.currentUser.getIdToken(true);syncStage="baixar as ocorrências do Apps Script";
    const raw=extractArray(await fetchJsonFresh(occurrencesSyncUrl));if(!raw.length)throw new Error("Base de ocorrências vazia");
    syncStage="carregar o índice de alunos";
    const indexSnapshot=await getDoc(doc(db,"settings","student-index")),byRa=new Map(),byRaFull=new Map(),byName=new Map(),indexedStudents=Object.values(indexSnapshot.data()?.students||{}),indexStudent=student=>{const base=normalizeRa(student.ra),full=base+normalizeRa(student.digit);if(base)byRa.set(base,student);if(full)byRaFull.set(full,student);if(normalize(student.name))byName.set(normalize(student.name),student)};
    if(indexedStudents.length)indexedStudents.forEach(indexStudent);else{const studentsSnapshot=await getDocs(collection(db,"students"));studentsSnapshot.docs.forEach((entry,index)=>indexStudent(adaptStudent({id:entry.id,...entry.data()},index)))}
    const prepared=new Map(),duplicateOrdinals=new Map();
    for(let index=0;index<raw.length;index++){
      const source=raw[index],item=adaptOccurrence(source,index),occurrenceRa=normalizeRa(item.studentRa),student=byRa.get(occurrenceRa)||byRaFull.get(occurrenceRa)||byName.get(normalize(item.studentName));item.eventTime=timeOnly(item.eventTime);
      if(student){item.studentId=student.id;item.studentName=student.name;item.studentRa=student.ra;item.classId=student.classId;item.tutor=student.tutor||item.tutor}
      if(!item.studentName&&!item.studentRa)continue;
      const registeredAt=field(source,["dataRegistro","Data Registro","createdAt"]),registeredTime=timeOnly(field(source,["horaRegistro","Hora Registro"])),signature=[item.studentRa,item.studentName,item.classId,item.tutor,item.eventDate,item.eventTime,item.teacher,item.description,item.actionTaken,registeredAt,registeredTime].map(normalize).join("|");
      const ordinal=(duplicateOrdinals.get(signature)||0)+1;duplicateOrdinals.set(signature,ordinal);const id=await occurrenceId(item.studentRa,item.eventDate,item.eventTime,signature+"|copia:"+ordinal);
      prepared.set(id,{id,data:{studentId:item.studentId,studentRa:item.studentRa,studentName:item.studentName,classId:item.classId,tutor:item.tutor,eventDate:item.eventDate,eventTime:item.eventTime,category:item.category,description:item.description,teacher:item.teacher,actionTaken:item.actionTaken,registeredAt:String(registeredAt||""),registeredTime,sourceRow:index+2,sourceCopy:ordinal,createdAt:occurrenceTimestamp(registeredAt||item.eventDate),source:"google-sheets",syncedAt:serverTimestamp()}})
    }
    syncStage="preparar a migração integral das ocorrências";const previousSync=await getDoc(doc(db,"settings","occurrences-sync")),importedIds=[...prepared.keys()],cleanupOperations=[];
    if(Array.isArray(previousSync.data()?.importedIds)){previousSync.data().importedIds.forEach(id=>{if(!prepared.has(id))cleanupOperations.push({type:"delete",ref:doc(db,"occurrences",id)})})}else{const oldImport=await getDocs(query(collection(db,"occurrences"),where("source","==","google-sheets")));oldImport.docs.forEach(entry=>cleanupOperations.push({type:"delete",ref:entry.ref}))}
    syncStage="gravar "+prepared.size+" ocorrências no Firestore";const importOperations=[...prepared.values()].map(item=>({type:"set",ref:doc(db,"occurrences",item.id),data:item.data,options:{merge:true}}));await commitOperations([...cleanupOperations,...importOperations]);const written=prepared.size;
    syncStage="salvar o resumo da sincronização";
    await setDoc(doc(db,"settings","occurrences-sync"),{records:written,importedIds,sourceUrl:occurrencesSyncUrl,syncedAt:serverTimestamp(),syncedBy:"fernando@villani.app",importMode:"full-sheet-v1"},{merge:true});
    state.occurrencePages=[];await resetOccurrencePagination();$("#connectionText").textContent="Ocorrências atualizadas";$("#lastOccurrenceSyncText").textContent="Ocorrências: concluída agora · "+written+" registros integrais da planilha.";message(written+" ocorrências sincronizadas integralmente, incluindo repetições da planilha.")
  }catch(error){console.error("Falha ao "+syncStage,error);$("#connectionText").textContent="Falha na sincronização";const detail=[error.code,error.message].filter(Boolean).join(" — ");message("Falha ao "+syncStage+(detail?": "+detail:"")+".",true)}finally{button.disabled=false;button.textContent="Sincronizar ocorrências"}
};
$("#masterForm").onsubmit=async event=>{event.preventDefault();const error=$("#masterError"),button=event.submitter;error.hidden=true;button.disabled=true;button.textContent="Entrando...";try{if(normalize($("#masterUser").value)!=="fernando")throw new Error();await signOut(auth);await signInWithEmailAndPassword(auth,"fernando@villani.app",$("#masterPassword").value);$("#masterDialog").close();message("Modo master ativado.");openTab("occurrences");resetOccurrencePagination()}catch{error.textContent="Usuário ou senha incorretos.";error.hidden=false;try{await signInAnonymously(auth)}catch{}}finally{button.disabled=false;button.textContent="Entrar como Fernando"}};
$("#editForm").onsubmit=async event=>{event.preventDefault();if(!state.isMaster)return;const button=event.submitter,id=$("#editId").value;button.disabled=true;try{await updateDoc(doc(db,"occurrences",id),{eventDate:$("#editDate").value,eventTime:$("#editTime").value,category:$("#editCategory").value,teacher:$("#editTeacher").value.trim(),description:$("#editDescription").value.trim(),actionTaken:$("#editAction").value.trim(),updatedAt:serverTimestamp(),updatedBy:"fernando@villani.app"});$("#editDialog").close();message("Ocorrência atualizada.");resetOccurrencePagination()}catch(error){console.error(error);message("Não foi possível editar.",true)}finally{button.disabled=false}};
$("#deleteOccurrence").onclick=async()=>{if(!state.isMaster)return;const id=$("#editId").value,item=state.occurrences.find(entry=>entry.id===id);if(!item||!confirm(`Apagar definitivamente a ocorrência de ${item.studentName}?`))return;try{await deleteDoc(doc(db,"occurrences",id));$("#editDialog").close();message("Ocorrência apagada.");resetOccurrencePagination()}catch(error){console.error(error);message("Não foi possível apagar.",true)}};
$("#occurrenceForm").onsubmit=async event=>{event.preventDefault();const student=findStudent($("#formStudent").value);if(!student)return;const values={eventDate:$("#eventDate").value,eventTime:$("#eventTime").value,category:$("#category").value,teacher:$("#teacher").value.trim(),description:$("#description").value.trim(),actionTaken:$("#actionTaken").value.trim()},button=$("#saveButton"),result=$("#saveResult"),whatsappWindow=window.open("","_blank");button.disabled=true;button.textContent="Salvando...";result.hidden=true;try{if(!auth.currentUser)await signInAnonymously(auth);const id=await occurrenceId(student.ra,values.eventDate,values.eventTime,values.description),reference=doc(db,"occurrences",id);if((await getDoc(reference)).exists()){whatsappWindow?.close();result.textContent="Esta ocorrência já foi registrada.";result.hidden=false;return}await setDoc(reference,{studentId:student.id,studentRa:student.ra,studentName:student.name,classId:student.classId,tutor:student.tutor||"",...values,createdAt:serverTimestamp(),createdBy:auth.currentUser?.uid||"anonymous",source:"github-pages"});const link=whatsappLink(student,values);result.innerHTML=`Ocorrência salva. <a target="_blank" rel="noreferrer" href="${link}">Abrir WhatsApp novamente</a>`;result.hidden=false;state.occurrencePages=[];message("Ocorrência gravada no Firebase. Abrindo o WhatsApp...");if(whatsappWindow)whatsappWindow.location.replace(link);else window.location.href=link}catch(error){whatsappWindow?.close();console.error(error);result.textContent="Não foi possível salvar.";result.hidden=false}finally{button.disabled=false;button.textContent="Salvar ocorrência no Firebase"}};

async function start(){fillClassSelectors();onAuthStateChanged(auth,setMasterInterface);try{await signInAnonymously(auth)}catch{$("#connectionText").textContent="Consulta pública ativa"}try{const count=await getCountFromServer(query(collection(db,"students"),where("active","==",true)));$("#studentCount").textContent=count.data().count}catch{$("#studentCount").textContent="—"}}
start();
