import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signInAnonymously, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { collection, deleteDoc, doc, getCountFromServer, getDoc, getDocs, getFirestore, limit, orderBy, query, serverTimestamp, setDoc, startAfter, Timestamp, updateDoc, where, writeBatch } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
import { firebaseConfig, occurrencesSyncUrl, studentsSyncUrl } from "./firebase-config.js?v=20260803-6";

const CLASSES=["6A","6B","6C","7A","7B","7C","8A","8B","8C","9A","9B","9C","1A","1B","1C","1D","2A","2B","3A"];
const PAGE_SIZE=5;
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const state={studentCache:new Map(),students:[],currentClass:"",isMaster:false,occurrences:[],occurrenceDocs:[],occurrencePages:[],occurrencePage:0,occurrenceTotal:0,selectedId:""};
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const escapeHtml=value=>{const div=document.createElement("div");div.textContent=value??"";return div.innerHTML};
const normalize=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\s+/g," ").trim();
const normalizeRa=value=>String(value||"").replace(/\D/g,"").replace(/^0+(?=\d)/,"");
const dateOnly=value=>{const text=String(value||"").slice(0,10);return text.includes("/")?text.split("/").reverse().join("-"):text};
const formatDate=value=>{if(!value)return"—";const[y,m,d]=dateOnly(value).split("-");return d&&m&&y?`${d}/${m}/${y}`:value};
const extractArray=json=>Array.isArray(json)?json:Object.values(json||{}).find(Array.isArray)||[];
const timeOnly=value=>{const text=String(value||"");if(/^\d{1,2}:\d{2}/.test(text))return text.slice(0,5);const date=new Date(text);return Number.isNaN(date.getTime())?text:date.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit",timeZone:"America/Sao_Paulo"})};

function occurrenceTimestamp(value){
  const text=String(value||"").trim();let date;
  if(/^\d{1,2}\/\d{1,2}\/\d{4}/.test(text)){const[d,m,y]=text.split(/[\/\s]/);date=new Date(Number(y),Number(m)-1,Number(d))}else date=new Date(text);
  return Number.isNaN(date.getTime())?Timestamp.fromDate(new Date(2000,0,1)):Timestamp.fromDate(date)
}
const canonicalStudentId=student=>`ra-${normalizeRa(student.ra)}-${normalizeRa(student.digit)||"0"}`;
async function commitOperations(operations){for(let start=0;start<operations.length;start+=350){const batch=writeBatch(db);for(const operation of operations.slice(start,start+350)){if(operation.type==="delete")batch.delete(operation.ref);else batch.set(operation.ref,operation.data,operation.options||{})}await batch.commit()}}

function adaptStudent(raw,index){const ra=String(raw.ra||raw.RA||""),digit=String(raw.digit||raw.digito||""),status=normalize(raw.situacao||raw.status),explicitActive=raw.active;const active=explicitActive!==undefined?[true,"true",1,"1","sim","ativo"].includes(typeof explicitActive==="string"?normalize(explicitActive):explicitActive):(status?status==="ativo":true);return{id:String(raw.id||`ra-${normalizeRa(ra)}-${normalizeRa(digit)||index}`),name:String(raw.name||raw.nome||"Aluno sem nome"),ra,digit,classId:String(raw.classId||raw.sala||raw.Sala||"").toUpperCase(),number:Number(raw.number||raw.numero)||"",tutor:String(raw.tutor||raw.Tutor||""),elective:String(raw.elective||raw.eletiva1||raw.elective1||""),birthday:String(raw.birthday||raw.nascimento||""),photoUrl:String(raw.photoUrl||raw.foto||""),active}}
function field(raw,keys){for(const key of keys)if(raw[key]!==undefined&&raw[key]!==null)return raw[key];return""}
function adaptOccurrence(raw,index){const ra=String(field(raw,["studentRa","ra","RA"])),name=String(field(raw,["studentName","nome","Nome do Aluno","aluno"]));return{id:String(raw.id||`occ-${index}`),studentId:String(raw.studentId||`ra-${normalizeRa(ra)}`),studentRa:ra,studentName:name,classId:String(field(raw,["classId","Sala","sala"])).toUpperCase(),tutor:String(field(raw,["tutor","Tutor"])),eventDate:dateOnly(field(raw,["eventDate","Data do Fato","dataFato"])),eventTime:String(field(raw,["eventTime","Hora do Fato","horaFato"])),category:String(field(raw,["category","Categoria","tipo"])||"Registro geral"),description:String(field(raw,["description","Descrição","descricao"])),teacher:String(field(raw,["teacher","Professor","professor"])),actionTaken:String(field(raw,["actionTaken","Ação Tomada","acao"]))}}
function drivePhoto(value){if(!value)return"";const text=String(value).trim(),match=text.match(/(?:\/d\/|id=)([-\w]{15,})/),id=match?.[1]||(/^[-\w]{15,}$/.test(text)?text:"");return id?`https://lh3.googleusercontent.com/d/${id}=w600`:text}
function avatar(student,large=false){const src=drivePhoto(student.photoUrl);return src?`<img class="avatar ${large?"large":""}" src="${escapeHtml(src)}" alt="Foto de ${escapeHtml(student.name)}" loading="lazy" data-photo="${escapeHtml(src)}" data-name="${escapeHtml(student.name)}">`:`<span class="avatar fallback ${large?"large":""}">${escapeHtml(student.name.slice(0,2).toUpperCase())}</span>`}
function message(text,error=false){const el=$("#message");el.textContent=text;el.classList.toggle("error",error);el.hidden=!text;if(text)window.scrollTo({top:0,behavior:"smooth"})}
function classOptions(){return CLASSES.map(value=>`<option value="${value}">${value}</option>`).join("")}
function fillClassSelectors(){["classFilter","occurrenceClass","reportClass","formClass"].forEach(id=>$("#"+id).insertAdjacentHTML("beforeend",classOptions()));$("#classCount").textContent=`${CLASSES.length} turmas disponíveis`}

async function loadStudentsForClass(classId,{fresh=false}={}){
  if(!classId)return[];if(!fresh&&state.studentCache.has(classId))return state.studentCache.get(classId);
  const snapshot=await getDocs(query(collection(db,"students"),where("classId","==",classId)));
  const students=snapshot.docs.map((entry,index)=>adaptStudent({id:entry.id,...entry.data()},index)).filter(item=>item.active).sort((a,b)=>(a.number||999)-(b.number||999)||a.name.localeCompare(b.name,"pt-BR"));
  state.studentCache.set(classId,students);return students;
}

async function selectStudentClass(classId,fresh=false){
  state.currentClass=classId;$("#studentSearch").disabled=!classId;if(!classId){state.students=[];$("#studentGrid").innerHTML=`<div class="empty">Selecione uma turma para carregar somente os alunos solicitados.</div>`;$("#resultCount").textContent="0 resultados";return}
  $("#studentGrid").innerHTML=`<div class="empty">Carregando ${classId}...</div>`;
  try{state.students=await loadStudentsForClass(classId,{fresh});renderStudents();$("#studentCount").textContent=state.students.length;$("#classCount").textContent=`alunos carregados da turma ${classId}`}
  catch(error){console.error(error);$("#studentGrid").innerHTML=`<div class="empty">Não foi possível carregar a turma. Confirme se a sincronização do Villani criou os documentos na coleção students.</div>`}
}

function renderStudents(){const term=normalize($("#studentSearch").value),list=state.students.filter(item=>!term||normalize(`${item.name} ${item.ra}`).includes(term));$("#resultCount").textContent=`${list.length} resultados`;$("#studentGrid").innerHTML=list.length?list.map(student=>`<article class="student-card">${avatar(student)}<div><header><h3>${escapeHtml(student.name)}</h3><b>${escapeHtml(student.classId)}</b></header><p>RA ${escapeHtml(student.ra||"—")} ${student.digit?`–${escapeHtml(student.digit)}`:""}</p><dl><div><dt>Tutor</dt><dd>${escapeHtml(student.tutor||"—")}</dd></div><div><dt>Eletiva</dt><dd>${escapeHtml(student.elective||"—")}</dd></div></dl><footer><button data-open-report="${escapeHtml(student.id)}" data-class="${student.classId}">Ver boletim</button><button class="secondary" data-open-occurrences="${escapeHtml(student.id)}" data-class="${student.classId}">Ver ocorrências</button></footer></div></article>`).join(""):`<div class="empty">Nenhum aluno encontrado nesta turma.</div>`;bindDynamic()}

function studentOptions(students){return`<option value="">Todos os alunos</option>`+students.map(item=>`<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)} · RA ${escapeHtml(item.ra)}</option>`).join("")}
async function populateStudentsFor(selectId,classId,allLabel="Selecione o aluno"){
  const select=$("#"+selectId);select.disabled=true;select.innerHTML=`<option value="">Carregando...</option>`;if(!classId){select.innerHTML=`<option value="">${allLabel}</option>`;return[]}
  try{const students=await loadStudentsForClass(classId);select.innerHTML=studentOptions(students);if(allLabel!=="Todos os alunos")select.options[0].textContent=allLabel;select.disabled=false;return students}catch{select.innerHTML=`<option value="">Erro ao carregar</option>`;return[]}
}
function findStudent(id){for(const students of state.studentCache.values()){const found=students.find(item=>item.id===id);if(found)return found}return null}

function occurrenceBaseConstraints(){const constraints=[];const studentId=$("#occurrenceStudent").value,classId=$("#occurrenceClass").value;if(studentId)constraints.push(where("studentId","==",studentId));else if(classId)constraints.push(where("classId","==",classId));return constraints}
function occurrenceQuery(afterDocument=null,pageSize=PAGE_SIZE){const constraints=[...occurrenceBaseConstraints(),orderBy("createdAt","desc")];if(afterDocument)constraints.push(startAfter(afterDocument));constraints.push(limit(pageSize));return query(collection(db,"occurrences"),...constraints)}

async function resetOccurrencePagination(){state.occurrencePages=[];state.occurrencePage=0;$("#occurrenceList").innerHTML=`<div class="empty">Carregando ocorrências...</div>`;try{const countSnapshot=await getCountFromServer(query(collection(db,"occurrences"),...occurrenceBaseConstraints()));state.occurrenceTotal=countSnapshot.data().count;await loadOccurrencePage(0)}catch(error){console.error(error);$("#occurrenceList").innerHTML=`<div class="empty">Não foi possível consultar. Se você combinou filtros, crie o índice indicado pelo Firebase.</div>`}}
async function loadOccurrencePage(index){
  if(index<0)return;if(state.occurrencePages[index]){showOccurrencePage(index);return}
  const previous=index>0?state.occurrencePages[index-1]:null,after=previous?.docs.at(-1)||null;$("#occurrenceList").innerHTML=`<div class="empty">Carregando página ${index+1}...</div>`;
  const snapshot=await getDocs(occurrenceQuery(after));const page={docs:snapshot.docs,items:snapshot.docs.map((entry,i)=>adaptOccurrence({id:entry.id,...entry.data()},i))};state.occurrencePages[index]=page;showOccurrencePage(index)
}
function showOccurrencePage(index){state.occurrencePage=index;const page=state.occurrencePages[index];state.occurrenceDocs=page.docs;state.occurrences=page.items;renderOccurrences();$("#occurrenceCount").textContent=`${state.occurrenceTotal} registros`;$("#occurrencePage").textContent=`Página ${index+1} de ${Math.max(1,Math.ceil(state.occurrenceTotal/PAGE_SIZE))}`;$("#previousOccurrence").disabled=index===0;$("#nextOccurrence").disabled=(index+1)*PAGE_SIZE>=state.occurrenceTotal||page.docs.length<PAGE_SIZE}
function renderOccurrences(){const term=normalize($("#occurrenceSearch").value),from=$("#dateFrom").value,to=$("#dateTo").value;const list=state.occurrences.filter(item=>(!term||normalize(`${item.studentName} ${item.studentRa} ${item.description}`).includes(term))&&(!from||item.eventDate>=from)&&(!to||item.eventDate<=to));$("#occurrenceList").innerHTML=list.length?list.map(item=>`<article class="occurrence ${state.isMaster?"master-occurrence":""}"><div class="date"><b>${escapeHtml(formatDate(item.eventDate).slice(0,5))}</b><span>${escapeHtml(item.eventTime||"—")}</span></div><div class="occ-body"><header><div><em>${escapeHtml(item.category)}</em><h3>${escapeHtml(item.studentName)}</h3><small>${escapeHtml(item.classId)} · RA ${escapeHtml(item.studentRa||"—")}</small></div>${state.isMaster?`<button class="edit-button" data-edit-occurrence="${escapeHtml(item.id)}">Editar</button>`:""}</header><p>${escapeHtml(item.description||"Sem descrição.")}</p><footer>${item.teacher?`<span>Professor: <b>${escapeHtml(item.teacher)}</b></span>`:""}${item.actionTaken?`<span>Ação: <b>${escapeHtml(item.actionTaken)}</b></span>`:""}</footer></div></article>`).join(""):`<div class="empty">Nenhuma ocorrência nesta página.</div>`;bindDynamic()}

async function loadReport(student){const content=$("#reportContent");content.className="report-wrap";content.innerHTML=`<div class="empty">Carregando boletim...</div>`;const suffixes=["apb","asb","atb","aqb"],terms=[];for(const suffix of suffixes){try{const response=await fetch(`${student.classId.toLowerCase()}${suffix}.json`,{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json(),values=Array.isArray(data)?data:Object.values(data);terms.push(values.find(item=>normalizeRa(item.ra)===normalizeRa(student.ra))||values.find(item=>normalize(item.nome||item.name)===normalize(student.name))||null)}catch{terms.push(null)}}const subjects=[...new Set(terms.flatMap(term=>term?.disciplinas?Object.keys(term.disciplinas):[]))];content.innerHTML=`<article class="profile">${avatar(student,true)}<div><em>ALUNO ATIVO</em><h2>${escapeHtml(student.name)}</h2><p>RA ${escapeHtml(student.ra||"—")} · Nº ${escapeHtml(student.number||"—")} · ${escapeHtml(student.classId)}</p><dl><div><dt>Tutor</dt><dd>${escapeHtml(student.tutor||"—")}</dd></div><div><dt>Eletiva</dt><dd>${escapeHtml(student.elective||"—")}</dd></div></dl></div></article>${subjects.length?`<div class="table-wrap"><table><thead><tr><th>Disciplina</th>${terms.map((_,i)=>`<th>${i+1}º bimestre</th>`).join("")}</tr></thead><tbody>${subjects.map(subject=>`<tr><td>${escapeHtml(subject)}</td>${terms.map(term=>{const data=term?.disciplinas?.[subject];return`<td><b>${escapeHtml(data?.nota??data?.media??"—")}</b><small>${escapeHtml(data?.faltas??0)} faltas</small></td>`}).join("")}</tr>`).join("")}</tbody></table></div>`:`<div class="empty">Nenhum JSON de boletim foi encontrado para ${escapeHtml(student.classId)}.</div>`}`;bindDynamic()}

async function occurrenceId(ra,date,time,description){const source=[normalizeRa(ra),date,time,normalize(description)].join("|"),bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(source));return`occ-${[...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,"0")).join("").slice(0,32)}`}
function whatsappNumber(classId){return/^(6|7|8|9)[ABC]$/i.test(String(classId).replace(/\s/g,""))?"5519997984511":"5519990020650"}
function whatsappLink(student,values){const text=["*OCORRÊNCIA ESCOLAR*","",`Aluno: ${student.name}`,`RA: ${student.ra}`,`Sala: ${student.classId}`,`Tutor: ${student.tutor||"Não informado"}`,"",`Data do fato: ${formatDate(values.eventDate)}`,`Hora: ${values.eventTime||"Não informada"}`,"",`Professor: ${values.teacher||"Não informado"}`,"","Descrição:",values.description,"","Ação tomada:",values.actionTaken||"Não informada"].join("\n");return`https://wa.me/${whatsappNumber(student.classId)}?text=${encodeURIComponent(text)}&app_absent=0`}

function bindDynamic(){$$('[data-photo]').forEach(img=>img.onclick=()=>{const dialog=$("#photoDialog");dialog.querySelector("img").src=img.dataset.photo;dialog.querySelector("strong").textContent=img.dataset.name;dialog.showModal()});$$('[data-open-report]').forEach(button=>button.onclick=async()=>{$("#reportClass").value=button.dataset.class;await populateStudentsFor("reportStudent",button.dataset.class);$("#reportStudent").value=button.dataset.openReport;openTab("report");loadReport(findStudent(button.dataset.openReport))});$$('[data-open-occurrences]').forEach(button=>button.onclick=async()=>{$("#occurrenceClass").value=button.dataset.class;await populateStudentsFor("occurrenceStudent",button.dataset.class,"Todos os alunos");$("#occurrenceStudent").value=button.dataset.openOccurrences;openTab("occurrences");resetOccurrencePagination()});$$('[data-edit-occurrence]').forEach(button=>button.onclick=()=>openOccurrenceEditor(button.dataset.editOccurrence))}
function openTab(id){$$('.view').forEach(view=>view.classList.toggle("active",view.id===id));$$('.tabs button').forEach(button=>button.classList.toggle("active",button.dataset.tab===id));window.scrollTo({top:0,behavior:"smooth"})}

async function updateSyncStatus(){
  if(!state.isMaster)return;
  try{
    const[studentsSnapshot,occurrencesSnapshot]=await Promise.all([getDoc(doc(db,"settings","students-sync")),getDoc(doc(db,"settings","occurrences-sync"))]);
    if(studentsSnapshot.exists()){const data=studentsSnapshot.data(),date=data.syncedAt?.toDate?data.syncedAt.toDate():null;$("#lastSyncText").textContent=`Alunos: ${date?date.toLocaleString("pt-BR"):"data indisponível"} · ${data.records||0} registros.`}
    if(occurrencesSnapshot.exists()){const data=occurrencesSnapshot.data(),date=data.syncedAt?.toDate?data.syncedAt.toDate():null;$("#lastOccurrenceSyncText").textContent=`Ocorrências: ${date?date.toLocaleString("pt-BR"):"data indisponível"} · ${data.records||0} registros.`}
  }catch{$("#lastSyncText").textContent="Não foi possível consultar as últimas sincronizações."}
}
function setMasterInterface(user){state.isMaster=user?.email==="fernando@villani.app";$("#masterButton").textContent=state.isMaster?"Fernando · Sair":"Acesso master";$("#masterButton").classList.toggle("active",state.isMaster);$("#masterTools").hidden=!state.isMaster;$("#connectionText").textContent=state.isMaster?"Modo master ativo":user?"Firebase conectado":"Consulta pública ativa";if(state.isMaster)updateSyncStatus();renderOccurrences()}
function openOccurrenceEditor(id){if(!state.isMaster)return;const item=state.occurrences.find(entry=>entry.id===id);if(!item)return;$("#editId").value=item.id;$("#editStudentLabel").textContent=`${item.studentName} · ${item.classId} · RA ${item.studentRa}`;$("#editDate").value=item.eventDate;$("#editTime").value=item.eventTime||"";$("#editCategory").value=item.category||"Registro geral";$("#editTeacher").value=item.teacher||"";$("#editDescription").value=item.description||"";$("#editAction").value=item.actionTaken||"";$("#editDialog").showModal()}

$("#classFilter").onchange=event=>selectStudentClass(event.target.value);$("#studentSearch").oninput=renderStudents;
$("#occurrenceClass").onchange=async event=>{await populateStudentsFor("occurrenceStudent",event.target.value,"Todos os alunos");resetOccurrencePagination()};$("#occurrenceStudent").onchange=resetOccurrencePagination;$("#occurrenceSearch").oninput=renderOccurrences;[$("#dateFrom"),$("#dateTo")].forEach(input=>input.onchange=renderOccurrences);
$("#previousOccurrence").onclick=()=>loadOccurrencePage(state.occurrencePage-1);$("#nextOccurrence").onclick=()=>loadOccurrencePage(state.occurrencePage+1);
$("#reportClass").onchange=event=>populateStudentsFor("reportStudent",event.target.value,"Selecione um aluno");$("#reportStudent").onchange=event=>{const student=findStudent(event.target.value);if(student)loadReport(student)};
$("#formClass").onchange=event=>populateStudentsFor("formStudent",event.target.value,"Selecione o aluno");$("#formStudent").onchange=event=>{const student=findStudent(event.target.value),box=$("#selectedStudent");if(!student){box.hidden=true;return}box.innerHTML=`${avatar(student)}<div><b>${escapeHtml(student.name)}</b><span>${student.classId} · RA ${escapeHtml(student.ra)} · Tutor ${escapeHtml(student.tutor||"—")}</span></div>`;box.hidden=false;bindDynamic()};
$$('.tabs button').forEach(button=>button.onclick=()=>{openTab(button.dataset.tab);if(button.dataset.tab==="occurrences"&&!state.occurrencePages.length)resetOccurrencePagination()});$("#eventDate").value=new Date().toISOString().slice(0,10);$("#photoDialog button").onclick=()=>$("#photoDialog").close();

$("#masterButton").onclick=async()=>{if(state.isMaster){await signOut(auth);await signInAnonymously(auth);message("Modo master encerrado.");return}$("#masterError").hidden=true;$("#masterPassword").value="";$("#masterDialog").showModal();setTimeout(()=>$("#masterPassword").focus(),100)};$("#masterDialog .dialog-close").onclick=()=>$("#masterDialog").close();$("#editDialog .dialog-close").onclick=()=>$("#editDialog").close();
$("#syncStudentsButton").onclick=async()=>{
  if(!state.isMaster||!confirm("Ler a base atual do Apps Script e atualizar os alunos no Firebase?"))return;
  const button=$("#syncStudentsButton");button.disabled=true;button.textContent="Sincronizando...";$("#connectionText").textContent="Atualizando alunos";
  try{
    const response=await fetch(studentsSyncUrl,{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const json=await response.json();const raw=Array.isArray(json)?json:Object.values(json).find(Array.isArray)||[];if(!raw.length)throw new Error("Base vazia");
    const uniqueStudents=new Map();raw.map(adaptStudent).filter(item=>item.active&&item.name&&normalizeRa(item.ra)).forEach(student=>{const id=canonicalStudentId(student);uniqueStudents.set(id,{...student,id,active:true})});
    const previousSync=await getDoc(doc(db,"settings","students-sync")),operations=[],activeIds=[...uniqueStudents.keys()];
    for(const student of uniqueStudents.values())operations.push({type:"set",ref:doc(db,"students",student.id),data:{...student,syncSource:"apps-script",syncedAt:serverTimestamp()},options:{merge:true}});
    if(Array.isArray(previousSync.data()?.activeIds)){previousSync.data().activeIds.forEach(id=>{if(!uniqueStudents.has(id))operations.push({type:"delete",ref:doc(db,"students",id)})})}else{const existingSnapshot=await getDocs(collection(db,"students"));existingSnapshot.docs.forEach(entry=>{if(!uniqueStudents.has(entry.id))operations.push({type:"delete",ref:entry.ref})})}
    await commitOperations(operations);const written=uniqueStudents.size,removed=operations.filter(item=>item.type==="delete").length;
    const studentIndex=Object.fromEntries([...uniqueStudents.values()].map(student=>[normalizeRa(student.ra),{id:student.id,name:student.name,ra:student.ra,classId:student.classId,tutor:student.tutor}]));
    const metadataBatch=writeBatch(db);for(const classId of CLASSES)metadataBatch.set(doc(db,"classes",classId),{id:classId,name:classId,year:2026,active:true,syncSource:"apps-script"},{merge:true});metadataBatch.set(doc(db,"settings","student-index"),{students:studentIndex,records:written,syncedAt:serverTimestamp()});metadataBatch.set(doc(db,"settings","students-sync"),{records:written,activeIds,sourceUrl:studentsSyncUrl,syncedAt:serverTimestamp(),syncedBy:"fernando@villani.app"},{merge:true});await metadataBatch.commit();
    state.studentCache.clear();if(state.currentClass)await selectStudentClass(state.currentClass,true);$("#studentCount").textContent=written;$("#connectionText").textContent="Sincronização concluída";$("#lastSyncText").textContent=`Sincronização concluída agora · ${written} alunos ativos.`;message(`${written} alunos ativos mantidos; ${removed} documentos inativos, antigos ou duplicados removidos.`);
  }catch(error){console.error(error);$("#connectionText").textContent="Falha na sincronização";message("Não foi possível sincronizar. Confirme o endereço do Apps Script e publique as regras master.",true)}finally{button.disabled=false;button.textContent="Sincronizar alunos"}
};
$("#syncOccurrencesButton").onclick=async()=>{
  if(!state.isMaster||!confirm("Importar e atualizar no Firebase as ocorrências antigas da planilha?"))return;
  const button=$("#syncOccurrencesButton");let syncStage="renovar a credencial master";button.disabled=true;button.textContent="Sincronizando...";$("#connectionText").textContent="Atualizando ocorrências";
  try{
    await auth.currentUser.getIdToken(true);syncStage="baixar as ocorrências do Apps Script";
    const response=await fetch(occurrencesSyncUrl,{cache:"no-store"});if(!response.ok)throw new Error("HTTP "+response.status);const raw=extractArray(await response.json());if(!raw.length)throw new Error("Base de ocorrências vazia");
    syncStage="carregar o índice de alunos";
    const indexSnapshot=await getDoc(doc(db,"settings","student-index")),byRa=new Map(),byName=new Map(),indexedStudents=Object.values(indexSnapshot.data()?.students||{});
    if(indexedStudents.length)indexedStudents.forEach(student=>{byRa.set(normalizeRa(student.ra),student);byName.set(normalize(student.name),student)});else{const studentsSnapshot=await getDocs(collection(db,"students"));studentsSnapshot.docs.forEach((entry,index)=>{const student=adaptStudent({id:entry.id,...entry.data()},index);if(normalizeRa(student.ra))byRa.set(normalizeRa(student.ra),student);if(normalize(student.name))byName.set(normalize(student.name),student)})}
    const prepared=new Map();
    for(let index=0;index<raw.length;index++){
      const source=raw[index],item=adaptOccurrence(source,index),student=byRa.get(normalizeRa(item.studentRa))||byName.get(normalize(item.studentName));item.eventTime=timeOnly(item.eventTime);
      if(student){item.studentId=student.id;item.studentName=student.name;item.studentRa=student.ra;item.classId=student.classId;item.tutor=student.tutor||item.tutor}
      if(!item.studentName&&!item.studentRa)continue;
      const id=await occurrenceId(item.studentRa,item.eventDate,item.eventTime,item.description),registeredAt=field(source,["dataRegistro","Data Registro","createdAt"]);
      prepared.set(id,{id,data:{studentId:item.studentId,studentRa:item.studentRa,studentName:item.studentName,classId:item.classId,tutor:item.tutor,eventDate:item.eventDate,eventTime:item.eventTime,category:item.category,description:item.description,teacher:item.teacher,actionTaken:item.actionTaken,createdAt:occurrenceTimestamp(registeredAt||item.eventDate),source:"google-sheets",syncedAt:serverTimestamp()}})
    }
    syncStage="gravar "+prepared.size+" ocorrências no Firestore";const importOperations=[...prepared.values()].map(item=>({type:"set",ref:doc(db,"occurrences",item.id),data:item.data,options:{merge:true}}));await commitOperations(importOperations);const written=prepared.size;
    syncStage="salvar o resumo da sincronização";
    await setDoc(doc(db,"settings","occurrences-sync"),{records:written,sourceUrl:occurrencesSyncUrl,syncedAt:serverTimestamp(),syncedBy:"fernando@villani.app",deduplication:"deterministic-id"},{merge:true});
    state.occurrencePages=[];await resetOccurrencePagination();$("#connectionText").textContent="Ocorrências atualizadas";$("#lastOccurrenceSyncText").textContent="Ocorrências: concluída agora · "+written+" registros da planilha.";message(written+" ocorrências únicas sincronizadas sem varrer toda a coleção.")
  }catch(error){console.error("Falha ao "+syncStage,error);$("#connectionText").textContent="Falha na sincronização";const detail=[error.code,error.message].filter(Boolean).join(" — ");message("Falha ao "+syncStage+(detail?": "+detail:"")+".",true)}finally{button.disabled=false;button.textContent="Sincronizar ocorrências"}
};
$("#masterForm").onsubmit=async event=>{event.preventDefault();const error=$("#masterError"),button=event.submitter;error.hidden=true;button.disabled=true;button.textContent="Entrando...";try{if(normalize($("#masterUser").value)!=="fernando")throw new Error();await signOut(auth);await signInWithEmailAndPassword(auth,"fernando@villani.app",$("#masterPassword").value);$("#masterDialog").close();message("Modo master ativado.");openTab("occurrences");resetOccurrencePagination()}catch{error.textContent="Usuário ou senha incorretos.";error.hidden=false;try{await signInAnonymously(auth)}catch{}}finally{button.disabled=false;button.textContent="Entrar como Fernando"}};
$("#editForm").onsubmit=async event=>{event.preventDefault();if(!state.isMaster)return;const button=event.submitter,id=$("#editId").value;button.disabled=true;try{await updateDoc(doc(db,"occurrences",id),{eventDate:$("#editDate").value,eventTime:$("#editTime").value,category:$("#editCategory").value,teacher:$("#editTeacher").value.trim(),description:$("#editDescription").value.trim(),actionTaken:$("#editAction").value.trim(),updatedAt:serverTimestamp(),updatedBy:"fernando@villani.app"});$("#editDialog").close();message("Ocorrência atualizada.");resetOccurrencePagination()}catch(error){console.error(error);message("Não foi possível editar.",true)}finally{button.disabled=false}};
$("#deleteOccurrence").onclick=async()=>{if(!state.isMaster)return;const id=$("#editId").value,item=state.occurrences.find(entry=>entry.id===id);if(!item||!confirm(`Apagar definitivamente a ocorrência de ${item.studentName}?`))return;try{await deleteDoc(doc(db,"occurrences",id));$("#editDialog").close();message("Ocorrência apagada.");resetOccurrencePagination()}catch(error){console.error(error);message("Não foi possível apagar.",true)}};
$("#occurrenceForm").onsubmit=async event=>{event.preventDefault();const student=findStudent($("#formStudent").value);if(!student)return;const values={eventDate:$("#eventDate").value,eventTime:$("#eventTime").value,category:$("#category").value,teacher:$("#teacher").value.trim(),description:$("#description").value.trim(),actionTaken:$("#actionTaken").value.trim()},button=$("#saveButton"),result=$("#saveResult");button.disabled=true;button.textContent="Salvando...";result.hidden=true;try{if(!auth.currentUser)await signInAnonymously(auth);const id=await occurrenceId(student.ra,values.eventDate,values.eventTime,values.description),reference=doc(db,"occurrences",id);if((await getDoc(reference)).exists()){result.textContent="Esta ocorrência já foi registrada.";result.hidden=false;return}await setDoc(reference,{studentId:student.id,studentRa:student.ra,studentName:student.name,classId:student.classId,tutor:student.tutor||"",...values,createdAt:serverTimestamp(),createdBy:auth.currentUser?.uid||"anonymous",source:"github-pages"});result.innerHTML=`Ocorrência salva. <a target="_blank" rel="noreferrer" href="${whatsappLink(student,values)}">Enviar pelo WhatsApp</a>`;result.hidden=false;state.occurrencePages=[];message("Ocorrência gravada no Firebase.")}catch(error){console.error(error);result.textContent="Não foi possível salvar.";result.hidden=false}finally{button.disabled=false;button.textContent="Salvar ocorrência no Firebase"}};

async function start(){fillClassSelectors();onAuthStateChanged(auth,setMasterInterface);try{await signInAnonymously(auth)}catch{$("#connectionText").textContent="Consulta pública ativa"}try{const count=await getCountFromServer(query(collection(db,"students"),where("active","==",true)));$("#studentCount").textContent=count.data().count}catch{$("#studentCount").textContent="—"}}
start();
